Demo: GrabImage_Callback.cpp
	g++ -g -m32 -o GrabImage_Callback GrabImage_Callback.cpp -I../../../../../include -Wl,-rpath=$(MVCAM_COMMON_RUNENV)/32 -L$(MVCAM_COMMON_RUNENV)/32 -lMvCameraControl
	

clean:
	rm GrabImage_Callback -rf
