Demo: Events_Interface.cpp
	g++ -g -o Events_Interface Events_Interface.cpp -I../../../../../include -Wl,-rpath=$(MVCAM_COMMON_RUNENV)/64 -L$(MVCAM_COMMON_RUNENV)/64 -lMvCameraControl 
	

clean:
	rm Events_Interface -rf
