Demo: ParametrizeCamera_AreaScanIOSettings.cpp
	g++ -g -o ParametrizeCamera_AreaScanIOSettings ParametrizeCamera_AreaScanIOSettings.cpp -I../../../../../include -Wl,-rpath=$(MVCAM_COMMON_RUNENV)/64 -L$(MVCAM_COMMON_RUNENV)/64 -lMvCameraControl -lpthread 
	

clean:
	rm ParametrizeCamera_AreaScanIOSettings -rf
