Demo: HighBandwidthDecode.cpp
	g++ -g -m32 -o HighBandwidthDecode HighBandwidthDecode.cpp -I../../../../../include -Wl,-rpath=$(MVCAM_COMMON_RUNENV)/32 -L$(MVCAM_COMMON_RUNENV)/32 -lMvCameraControl -lpthread
	

clean:
	rm HighBandwidthDecode -rf