Demo: MultiLightCtrl_ImageStitching.cpp
	g++ -g -o MultiLightCtrl_ImageStitching MultiLightCtrl_ImageStitching.cpp -I../../../../../include -Wl,-rpath=$(MVCAM_COMMON_RUNENV)/32 -L$(MVCAM_COMMON_RUNENV)/32 -lMvCameraControl -lpthread 
	

clean:
	rm MultiLightCtrl_ImageStitching -rf
