Demo: RawDataFormatConvert.cpp
	g++ -g -m32  -o RawDataFormatConvert RawDataFormatConvert.cpp -I../../../../../include -I/usr/include/opencv4 -Wl,-rpath=$(MVCAM_COMMON_RUNENV)/32 -L$(MVCAM_COMMON_RUNENV)/32 -lMvCameraControl  -lopencv_core -lopencv_imgproc -lopencv_imgcodecs
	

clean:
	rm RawDataFormatConvert -rf

