Demo: ConfigLightController.cpp
	g++ -g -o ConfigLightController ConfigLightController.cpp -I../../../../../include -Wl,-rpath=$(MVCAM_COMMON_RUNENV)/64 -L$(MVCAM_COMMON_RUNENV)/64 -lMvCameraControl -lpthread
	

clean:
	rm ConfigLightController -rf
