Demo: QuickSoftwareTrigger.cpp
	g++ -g -o QuickSoftwareTrigger QuickSoftwareTrigger.cpp -I../../../../../include -Wl,-rpath=$(MVCAM_COMMON_RUNENV)/64 -L$(MVCAM_COMMON_RUNENV)/64 -lMvCameraControl -lpthread
	

clean:
	rm QuickSoftwareTrigger -rf
