Demo: ParametrizeCamera_LineScanIOSettings.cpp
	g++ -g -o ParametrizeCamera_LineScanIOSettings ParametrizeCamera_LineScanIOSettings.cpp -I../../../../../include -Wl,-rpath=$(MVCAM_COMMON_RUNENV)/64 -L$(MVCAM_COMMON_RUNENV)/64 -lMvCameraControl -lpthread 
	

clean:
	rm ParametrizeCamera_LineScanIOSettings -rf
