robot:
  cameras:
    left:
      type: opencv
      device_id: /dev/video30
      image_shape: [480, 640]
      fps: 30
      fourcc: MJPG
      backend: v4l2
    right:
      type: opencv
      device_id: /dev/video28
      image_shape: [480, 640]
      fps: 30
      fourcc: MJPG
      backend: v4l2
