Demo: LineScanSoftwareTrigger.cpp
	g++ -g -o LineScanSoftwareTrigger LineScanSoftwareTrigger.cpp -I../../../../../include -Wl,-rpath=$(MVCAM_COMMON_RUNENV)/64 -L$(MVCAM_COMMON_RUNENV)/64 -lMvCameraControl -lpthread 
	

clean:
	rm LineScanSoftwareTrigger -rf
