Demo: RawDataFormatConvert.cpp
	g++ -g -o RawDataFormatConvert RawDataFormatConvert.cpp -I../../../../../include -I/usr/include/opencv4 -Wl,-rpath=$(MVCAM_COMMON_RUNENV)/64 -L$(MVCAM_COMMON_RUNENV)/64 -lMvCameraControl  -lopencv_core -lopencv_imgproc -lopencv_imgcodecs
	

clean:
	rm RawDataFormatConvert -rf

