Demo: HighBandwidthDecode.cpp
	g++ -g -o HighBandwidthDecode HighBandwidthDecode.cpp -I../../../../../include -Wl,-rpath=$(MVCAM_COMMON_RUNENV)/64 -L$(MVCAM_COMMON_RUNENV)/64 -lMvCameraControl -lpthread
	

clean:
	rm HighBandwidthDecode -rf